apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      volumes:
        - name: vol
          emptyDir: {}
      serviceAccountName: default
      containers:
        - name: devsecops-container
          image: masudrana09/numeric-app:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /tmp
              name: vol
          securityContext:
            runAsUser: k8s-pipeline
            runAsGroup: pipeline
            
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: devsecops-svc
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30080   # optional
  selector:
    app: devsecops
  type: NodePort