apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      volumes:
        - name: vol
          emptyDir: {}
      serviceAccountName: default
      containers:
        - name: devsecops-container
          image: your-dockerhub-username/your-image-name:latest
          ports:
            - containerPort: 8082
          volumeMounts:
            - mountPath: /tmp
              name: vol
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: devsecops-svc
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
      nodePort: 30080   # optional
  selector:
    app: devsecops
  type: NodePort