apiVersion: v1
kind: Service
metadata:
  name: devsecops-service
  labels:
    app: devsecops
spec:
  selector:
    app: devsecops
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
